#include "main.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "gba.h"
#include <time.h>
/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
#include "images/garbage.h"
#include "images/GTFBALL.h"
#include "images/FBALL.h"
#include "images/FBALL3.h"
#include "images/red.h"
#include "images/START2.h"
#include "images/Field.h"
#include "images/WIN.h"
#include "images/Trophy.h"

/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
enum gba_state {
  START,
  MIDDLE,
  PLAY,
  WINNER,
  //LOSE,
  EXIT,
};

int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;
  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;
  int xloc = 72;
  int yloc = 0;
  int oldx = xloc;
  int oldy = yloc;
  // Load initial application state
  enum gba_state state = START;
  //int enter_down = 0;
  while (1) {
    currentButtons = BUTTONS; // Load the current state of the buttons
    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw
    waitForVBlank();
    switch (state) {
      case START:
      waitForVBlank();
      drawFullScreenImageDMA(START2);
      drawString(5,50,"WELCOME TO GT FOOTBALL!",BLACK);
      drawString(15,10,"MOVE THE FOOTBALL TO ENDZONE TO WIN!",YELLOW);
      drawString(140,90,"GOOD LUCK!",YELLOW);
      drawString(150,60,"PRESS ENTER TO BEGIN!",BLACK);
      waitForVBlank();
      state = MIDDLE;
        break;
      case MIDDLE:
        xloc = 72;//set back to 72
        yloc = 0;//set back to 0
        if(!KEY_DOWN(BUTTON_START, previousButtons) && KEY_DOWN(BUTTON_START, currentButtons)){
          //drawRectDMA(0,0,240,160,BLACK);
          drawFullScreenImageDMA(Field);
          drawRectDMA(0,220,20,160,RED);
          //drawRectDMA(xloc,yloc,10,10, GREEN);
          //drawRectDMA(0,220,20,160,RED);
          drawString(70,227,"U",BLACK);
          drawString(80,227,"G",BLACK);
          drawString(90,227,"A",BLACK);
          state = PLAY;
        }
      break;
      case PLAY:
        //if (!KEY_DOWN(BUTTON_START, previousButtons) && KEY_DOWN(BUTTON_START, currentButtons)) {
          oldx = xloc;
          oldy = yloc;
          if(KEY_DOWN(BUTTON_LEFT, currentButtons)){
            yloc--;
            if(yloc<0){
              yloc = 0;
            }
          }
          if(KEY_DOWN(BUTTON_RIGHT, currentButtons)){
            yloc++;
            if(yloc>200){
              yloc = 200;
            }
          }
          if(KEY_DOWN(BUTTON_UP, currentButtons)){
            xloc--;
            if(xloc<0){
              xloc = 0;
            }
          }
          if(KEY_DOWN(BUTTON_DOWN, currentButtons)){
            xloc++;
            if(xloc>145){
              xloc = 145;
            }
          }
          //drawFullScreenImageDMA(Field);
          //itoa(xloc,string, 10);
          char buffer[51];
          drawImageDMA(oldx,oldy,20,15, Field,1);
          drawImageDMA(0,70,50,15, Field,1);
          drawImageDMA(xloc,yloc,20,15, FBALL3,0);
          //drawString(2,2,"YARDS TO GO:",BLACK);
          drawString(2,2,buffer,BLACK);
			    sprintf(buffer, "YARDS TO GO: %d", (200-yloc)/2);
          
          //waitForVBlank();
          //state = WIN;
          if(yloc==200){
            state = WINNER;
          }
        if(!KEY_DOWN(BUTTON_SELECT, previousButtons) && KEY_DOWN(BUTTON_SELECT, currentButtons)){
          state = START;
        }
        //}
        break;
        // state = ?
      case WINNER:
        drawFullScreenImageDMA(Trophy);
        drawString(5,70,"WE HAVE A WINNER!",BLACK);
        drawString(15,10,"CONGRATS ON BEATING THE SCURVY DAWGS!",BLACK);
        //drawString(140,65,"Score: ___ Seconds",BLACK);
        drawString(140,40,"PRESS ENTER TO PLAY AGAIN!",BLACK);
        //waitForVBlank();
          state = EXIT;
        // state = ?
        break;
      case EXIT:
        if(!KEY_DOWN(BUTTON_START, previousButtons) && KEY_DOWN(BUTTON_START, currentButtons)){
          state = START;
        }
        if(!KEY_DOWN(BUTTON_SELECT, previousButtons) && KEY_DOWN(BUTTON_SELECT, currentButtons)){
          state = START;
        }
        // state = ?
        break;
    }

     previousButtons = currentButtons; // Store the current state of the buttons
   }

  UNUSED(previousButtons); // You can remove this once previousButtons is used

  return 0;
}
